project:
  name: "TXTdirect" # required
  state: "unstable" # unstable, beta, stable are supported
  image: "https://github.com/txtdirect/txtdirect/blob/master/logo.svg"
  website: "https://about.txtdirect.org"
  oneLiner: "DNS TXT-record based redirects"
  description: |
    Convenient and minimalistic DNS based redirects
  version: "v0.1.0"

vision:
  type: "community" # personal is the default.
  overview: |
    TXTdirect thrives to give back control and data to redirects.
  concept: "Instead of relying on external providers to control redirect data. TXTdirect uses data stored within your own DNS records and provides an easily switchable backend service/implementation."
  aim: "TXTdirect provides the specification for redirection records and a based implementation as caddy plugin."

supportLinks:
  documentation: "/docs"
  examples: "/examples"
  troubleshooting: "/docs/troubleshooting.md"

contributionLinks:
  issueTemplate: "/.github/ISSUE_TEMPLATE.md"
  starterIssues: "https://github.com/txtdirect/txtdirect/labels/starter%20issue"

email:
  commercialSupport: "support@okkur.io"
  security: "security@okkur.io"
  coc: "coc@okkur.io"

copyright:
  year: "2017"

cla:
  copyrightHolder: "Michael Grosser"

maintainers:
  - name: "Antoine Martin"
    nick: "alarsyo"
  - name: "Michael Grosser"
    nick: "stp-ip"

repo:
  link: "https://github.com/txtdirect/txtdirect/"
  type: "Github"

issueTemplate:
  questions:
  - "OS"
  - "Caddy version"

badges:
  - image: "https://img.shields.io/badge/state-unstable-red.svg"
    alt: "state"
  - image: "https://img.shields.io/github/release/txtdirect/txtdirect.svg"
    link: "https://github.com/txtdirect/txtdirect/releases"
    alt: "release"
  - image: "https://img.shields.io/github/license/txtdirect/txtdirect.svg"
    link: "LICENSE"
    alt: "license"
  - image: "https://travis-ci.org/txtdirect/txtdirect.svg?branch=master"
    alt: "Build Status"
    link: "https://travis-ci.org/txtdirect/txtdirect"
  - image: "https://goreportcard.com/badge/github.com/txtdirect/txtdirect"
    alt: "Go Report Card"
    link: "https://goreportcard.com/report/github.com/txtdirect/txtdirect"
